# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-18 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
