# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-24 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
