# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-22 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.TextField()),
                ('views', models.IntegerField(default=0)),
                ('image', models.FileField(upload_to='image')),
            ],
        ),
    ]
