# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-23 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
