# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-24 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0003_auto_20190424_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
