# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-21 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('description', models.TextField()),
                ('views', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
    ]
