# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-21 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debug',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
