# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-25 03:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_future_feature'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Future_Feature',
        ),
    ]
